name: project cicd flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: PostgresSQL
        run: docker run --restart always --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres

      - name: Wait for PostgreSQL to start
        run: |
          for i in {1..10}; do
            if docker exec postgres pg_isready -U postgres; then
              echo "PostgreSQL is ready!"
              break
            else
              echo "PostgreSQL is not ready, sleeping..."
              sleep 10
            fi
          done

      - name: Create Database
        run: docker exec postgres createdb -U postgres springboot-clean-architecture-example-test

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Run JaCoCo
        run: mvn jacoco:report
      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: jacoco
          path: target/site/jacoco/
